image_width: 1280
image_height: 720
camera_name: usb_cam
camera_matrix:
  rows: 3
  cols: 3
  data: [837.74574,   0.     , 696.89055,
           0.     , 832.82913, 346.16077,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.380429, 0.132772, -0.008058, -0.004651, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [634.57129,   0.     , 700.44595,   0.     ,
           0.     , 764.58453, 337.88785,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
